openapi:
  server:
    local: http://localhost:8080
    url: http://158.180.75.249

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v1/api-docs
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json