services:
  redis:
    container_name: munglog-redis
    image: redis:7.0.11
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - munglog_network

  postgres:
    container_name: munglog-db
    image: postgres:14.17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - munglog_network

  mongodb:
    container_name: munglog-mongodb
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    networks:
      - munglog_network

networks:
  munglog_network:
    driver: bridge
    name: munglog_network