services:
  redis:
    container_name: munglog-redis
    image: redis:7.0.11
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - munglog_network
    volumes:
      - redis_data:/data

  postgres:
    container_name: munglog-db
    image: postgres:14.17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - munglog_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    container_name: munglog-mongodb
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    networks:
      - munglog_network
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    container_name: munglog-rabbitmq
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"      # AMQP (spring.rabbitmq용)
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" # 관리 콘솔
      - "${RABBITMQ_STOMP_PORT}:61613"   # STOMP 브로커 포트
    networks:
      - munglog_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  munglog_network:
    driver: bridge
    name: munglog_network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
